"""add_lastname_firstname

Revision ID: 72949d7b0e6f
Revises: b716980c9cc6
Create Date: 2025-08-26 16:07:56.987960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72949d7b0e6f'
down_revision = 'b716980c9cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('firstname', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('firstname')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
