"""add base entity to roles

Revision ID: 793c056e5d5b
Revises: 9e0f95de84a8
Create Date: 2025-08-29 14:59:06.269607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793c056e5d5b'
down_revision = '9e0f95de84a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updatedate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deletedate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('deletedate')
        batch_op.drop_column('updatedate')
        batch_op.drop_column('createdate')

    # ### end Alembic commands ###
