"""add_tracking

Revision ID: f070840d1e5c
Revises: 3664806aa8c1
Create Date: 2025-08-27 14:16:35.188550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f070840d1e5c'
down_revision = '3664806aa8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updatedate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deletedate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True, default=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updatedate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deletedate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True, default=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('deletedate')
        batch_op.drop_column('updatedate')
        batch_op.drop_column('createdate')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('deletedate')
        batch_op.drop_column('updatedate')
        batch_op.drop_column('createdate')

    # ### end Alembic commands ###
